# Generated by Django 3.2.12 on 2022-05-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userprofile_langs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='langs',
        ),
    ]
