# Generated by Django 3.2.12 on 2022-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_activ',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активный'),
        ),
    ]
